### PR TITLE
Adding isMaster-gauge

### PR DESCRIPTION
**Pull request by miono**
Adding a gauge that is set to 1 if the namenode is master and 0 if it's
in standby-mode.

### CODE REVIEW

**Comment by wyukawa** [comment]
I feel the word ```master``` is weird because master namenode doesn't exist even though active namenode exists

**Comment by miono** [comment]
> I feel the word `master` is weird because master namenode doesn't exist even though active namenode exists

Would "isActive" be acceptable?

**Comment by wyukawa** [comment]
Yes. I think isActive is better

**Comment by miono** [comment]
I'll add another commit and squash them to a mergable single-commit PR.

**Comment by miono** [comment]
Do you see any problems with merging this? @wyukawa

**Comment by wyukawa** [comment]
Merged. Thanks!

**Pull request merged**
